import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import listingsRouter from "./listings";
import menuRouter from "./menu";
import reviewsRouter from "./reviews";
import reservationsRouter from "./reservations";
import ordersRouter from "./orders";
import savedRouter from "./saved";
import vendorRouter from "./vendor";
import adminRouter from "./admin";
import searchLogsRouter from "./search-logs";
import partnersRouter from "./partners";
import storageRouter from "./storage";
import eventsRouter from "./events";
import siteSettingsRouter from "./site-settings";
import categoriesRouter from "./categories";
import editorsPicksRouter from "./editors-picks";
import paymentsRouter from "./payments";
import pushTokensRouter from "./push-tokens";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(categoriesRouter);
router.use(listingsRouter);
router.use(menuRouter);
router.use(reviewsRouter);
router.use(reservationsRouter);
router.use(ordersRouter);
router.use(savedRouter);
router.use(vendorRouter);
router.use(adminRouter);
router.use(searchLogsRouter);
router.use(partnersRouter);
router.use(storageRouter);
router.use(eventsRouter);
router.use(siteSettingsRouter);
router.use(editorsPicksRouter);
router.use(paymentsRouter);
router.use(pushTokensRouter);

export default router;
